load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "stardoc_lib",
    srcs = ["stardoc.bzl"],
    visibility = ["//stardoc:__pkg__"],
    deps = [
        "@bazel_skylib//:bzl_library",
    ],
)
