package(default_visibility = ["//skydoc:__pkg__"])

py_library(
    name = "stubs",
    srcs = [
        "attr.py",
        "skylark_globals.py",
    ],
    deps = [
        "//skydoc:build_pb_py",
    ],
)
