package(default_visibility = ["//skydoc:__pkg__"])

py_library(
    name = "stubs",
    srcs = [
        "attr.py",
        "skylark_globals.py",
    ],
    deps = [
        "@bazel_tools//src/main/protobuf:build_pb_py",
    ],
)
