licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//skydoc:__pkg__"])

load("@io_bazel_rules_sass//sass:sass.bzl", "sass_binary")

sass_binary(
    name = "main",
    src = "main.scss",
)
