package(default_visibility = ["//skydoc:__pkg__"])

filegroup(
    name = "templates",
    srcs = [
        "attributes.jinja",
        "html.jinja",
        "markdown.jinja",
        "nav.jinja",
        "outputs.jinja",
        "overview.jinja",
        "toc.jinja",
    ],
)
